build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
- dockerfile_path: Dockerfile.assisted-service-build-ci
  from: src
  to: assisted-service
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: lint
  commands: make lint
  container:
    from: assisted-service
zz_generated_metadata:
  branch: prow_integration
  org: openshift
  repo: assisted-service
