build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
- dockerfile_path: Dockerfile.assisted-service-build-ci
  from: src
  to: assisted-service-builder
- dockerfile_path: Dockerfile.assisted-service
  from: src
  to: assisted-service
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: lint
  commands: |
    export GO111MODULE=on \
           TMP=/tmp \
           GOPATH=${TMP}/go \
           GOBIN=${TMP}/go/bin \
           GOFLAGS="" \
           GOPROXY=https://proxy.golang.org \
           GOROOT=/usr/local/go \
           GOLANGCI_LINT_CACHE=/tmp/go/.cache/go-build/.cache
    export PATH="${GOBIN}:${HOME}/.go/bin:${PATH}" \
           GOCACHE="${GOPATH}/pkg/mod" \
           XDG_CACHE_HOME=${TMP}
    make lint
  container:
    from: assisted-service-builder
zz_generated_metadata:
  branch: prow_integration
  org: openshift
  repo: assisted-service
