build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
- dockerfile_path: Dockerfile.assisted-service-build-ci
  from: src
  to: assisted-service
raw_steps:
- pipeline_image_cache_step:
    commands: |
        swagger generate server --template=stratoscale -f swagger.yaml --template-dir=go-swagger/generator/templates/contrib
        swagger generate client --template=stratoscale -f swagger.yaml --template-dir=go-swagger/generator/templates/contrib
    from: assisted-service
    to: assisted-service-swagger
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: swagger-server
  commands: swagger generate server --template=stratoscale -f swagger.yaml --template-dir=go-swagger/generator/templates/contrib
  container:
    from: assisted-service
- as: swagger-client
  commands: swagger generate client --template=stratoscale -f swagger.yaml --template-dir=go-swagger/generator/templates/contrib
  container:
    from: assisted-service
- as: lint
  commands: make lint
  container:
    from: assisted-service-swagger
zz_generated_metadata:
  branch: prow_integration
  org: openshift
  repo: assisted-service
